language: ruby
rvm: 2.5.1
addons:
  ssh_known_hosts:
    - 93.185.103.119:2222

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash ./travis/add-ssh-key.sh; fi
  - gem install bundler
  - bundle install --path vendor/bundle --full-index

script:
  - rm -rf _site
  - if [ "$TRAVIS_BRANCH" == "master" ]; then JEKYLL_ENV=production bundle exec jekyll build --config '_config.yml,_config.production.yml' --drafts --future; fi
  - if [ "$TRAVIS_BRANCH" == "production" ]; then JEKYLL_ENV=production bundle exec jekyll build --config '_config.yml,_config.production.yml'; fi
  - bundle exec htmlproofer --assume-extension --disable-external --url-ignore "#,#fn:1" --alt-ignore '/.*/' ./_site

deploy:
  - provider: script
    skip_cleanup: true
    script: if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then rsync -r --delete-after --quiet -e 'ssh -p 2222' $TRAVIS_BUILD_DIR/_site/ piratipardubice@93.185.103.119:/srv/pirati-tmp; fi
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then rsync -r --delete-after --quiet -e 'ssh -p 2222' $TRAVIS_BUILD_DIR/_site/ piratipardubice@93.185.103.119:/srv/pirati; fie
    on:
      branch: production

branches:
  only:
    - master
    - production

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
